import axiosInstance from '../hooks/useApi';

const BACKEND_ROOT = '/ai';
const USE_MOCK_DATA = true;

const mockDelay = (ms = 1000) => new Promise(resolve => setTimeout(resolve, ms));


export const getAiChat = async (message) => {
    if (USE_MOCK_DATA) {
        await mockDelay();
        return {
            reply: `[MOCK] This is a simulated AI response for: "${message}".\n\nI can help you with writing, coding, or summarizing documents.`
        };
    }
    try {
        const response = await axiosInstance.post(`${BACKEND_ROOT}/chat`, {'message': message});
        return response.data;
    } catch (error) {
        console.error('Error fetching documents:', error);
        throw error;
    }
}

export const generateContent = async (type, prompt) => {
    if (USE_MOCK_DATA) {
        await mockDelay(2000);
        return {
            content: `## [MOCK] Generated Content (${type})\n\n> Prompt: *${prompt}*\n\nHere is the content generated by the AI simulation:\n\n1. **Introduction**: This is a placeholder text to demonstrate the UI.\n2. **Details**: You can edit this text just like any other markdown content.\n3. **Conclusion**: The integration works perfectly!\n\n\`\`\`javascript\nconsole.log("Hello Mock World!");\n\`\`\``
        };
    }
    try {
        const response = await axiosInstance.post(`${BACKEND_ROOT}/generate`, { type, prompt });
        
        return response.data;
    } catch (error) {
        console.error('Error generating content:', error);
        throw error;
    }
}

export const refineContent = async (text, instruction) => {
    if (USE_MOCK_DATA) {
        await mockDelay(2000);
        return {
            content: `[MOCK REFINED]\n\n${text}\n\n--- Refined based on: "${instruction}" ---\n\nThis is the refined version of the text. The AI has improved clarity and grammar.`
        };
    }
    try {
        const response = await axiosInstance.post(`${BACKEND_ROOT}/refine`, { text, instruction });
        return response.data;
    } catch (error) {
        console.error('Error refining content:', error);
        throw error;
    }
}

export const suggestTags = async (content) => {
    if (USE_MOCK_DATA) {
        await mockDelay(1500);
        return {
            tags: ['ai-suggested', 'mock-tag', 'auto-generated']
        };
    }
    try {
        const response = await axiosInstance.post(`${BACKEND_ROOT}/tags`, { content });
        return response.data;
    } catch (error) {
        console.error('Error suggesting tags:', error);
        throw error;
    }
}

